In [ ]:
df = pd.read_csv('IndiaRainFallData.csv')
df = df.groupby('Year')['Annual_Rainfall(mm)'].mean().reset_index()
df['Annual_Rainfall(mm)'] = df['Annual_Rainfall(mm)'].round(2)

In [69]:
df

,State_Name,Lat,Long,Year,Annual_Rainfall(mm)
0,Andaman & Nicobar Islands,12.611240,92.831650,1901,3373.2
1,Andaman & Nicobar Islands,12.611240,92.831650,1902,3520.7
2,Andaman & Nicobar Islands,12.611240,92.831650,1903,2957.4
3,Andaman & Nicobar Islands,12.611240,92.831650,1904,3079.6
4,Andaman & Nicobar Islands,12.611240,92.831650,1905,2566.7
...,...,...,...,...,...
4182,Lakshadweep,10.160618,73.518509,2012,1405.5
4183,Lakshadweep,10.160618,73.518509,2013,1426.3
4184,Lakshadweep,10.160618,73.518509,2014,1395.0
4185,Lakshadweep,10.160618,73.518509,2015,1642.9
4186,Lakshadweep,10.160618,73.518509,2016,1065.7

In [ ]:

df

     Year  Annual_Rainfall(mm)
0    1901              1284.21
1    1902              1337.29
2    1903              1401.01
3    1904              1236.78
4    1905              1186.17
..    ...                  ...
112  2013              1475.15
113  2014              1244.36
114  2015              1280.57
115  2016              1273.71
116  2017              1357.40

[117 rows x 2 columns]

0      1284.21
1      1337.29
2      1401.01
3      1236.78
4      1186.17
        ...
112    1475.15
113    1244.36
114    1280.57
115    1273.71
116    1357.40
Name: Annual_Rainfall(mm), Length: 117, dtype: float64